### ISSUE TITLE
Follow talos configuration more closely

### ISSUE THREAD

**Issue by buroa** [budimanjojo/talhelper#105]
Right now, I can't do things like this: https://github.com/buroa/k8s-gitops/blob/master/talos/talconfig.yaml#L33 which are fully supported: https://www.talos.dev/v1.3/talos-guides/network/device-selector/

This tool should allow these types of things and not fail hard.

**Comment by budimanjojo** [comment]
Sorry, I really need to spend some time to improve the validation. Right now it looks messy AF T.T
Anyway, this should be fixed in the next release later today. Thanks for the bug report!
