### ISSUE TITLE
Apply patch to all nodes

### ISSUE THREAD

**Issue by wouterbouvy** [budimanjojo/talhelper#165]
Currently it's only possible to apply patches to either controlplane nodes or worker nodes. Would it be possible to apply patches to all nodes without having the same code in the talconfig.yaml twice? (Or referencing patch files in 2 places / using YAML anchors)
Talosctl provides this possibility with the option to use a patch for all nodes with the --config-patch option.

Reference: https://www.talos.dev/v1.5/talos-guides/configuration/patching/#configuration-patching-with-talosctl-cli

**Comment by budimanjojo** [comment]
Hello @wouterbouvy, this makes sense. I'll work on that real quick. Thank you!

**Comment by budimanjojo** [comment]
Done, the global config only allows `patches` and not the ancient `configPatches` and `inlinePatch` because they're only there for older compatibility and shouldn't be used anymore. This will be here on the next release. Thanks again!

**Comment by budimanjojo** [comment]
@wouterbouvy `v1.11.0` released with this addition, thank you!
