### ISSUE TITLE
Bug: talhelper fails to parse `talenv.yaml` if the yaml document delimiter is present

### ISSUE THREAD

**Issue by mirceanton** [budimanjojo/talhelper#220]
It seems that `talhelper` refuses to parse a `talenv.yaml` file if the yaml document delimiter is present:

```bash
mike@home-ops-devbox:/workspace/home-ops/infra/home-cluster$ ls -l
total 24
drwxr-xr-x 1 mike mike 4096 Nov 21 11:08 clusterconfig
drwxr-xr-x 1 mike mike 4096 Nov 19 18:38 patches
-rw-r--r-- 1 mike mike 3204 Nov 21 11:06 talconfig.yaml
-rw-r--r-- 1 mike mike   97 Nov 21 11:07 talenv.yaml
-rw-r--r-- 1 mike mike 8970 Nov 19 18:38 talsecret.sops.yaml
-rw-r--r-- 1 mike mike 4841 Nov 19 19:42 talsecret.yaml
mike@home-ops-devbox:/workspace/home-ops/infra/home-cluster$ cat talenv.yaml 
---
clusterName: home-ops
clusterEndpointIP: 10.0.10.10
clusterNetworkDomain: k8s.mirceanton.com
mike@home-ops-devbox:/workspace/home-ops/infra/home-cluster$ talhelper genconfig 
2023/11/21 11:09:28 failed to substitute env: variable ${clusterName} not set
```

But if I remove the `---` at the top of the file:

```bash
mike@home-ops-devbox:/workspace/home-ops/infra/home-cluster$ cat talenv.yaml 
clusterName: home-ops
clusterEndpointIP: 10.0.10.10
clusterNetworkDomain: k8s.mirceanton.com
mike@home-ops-devbox:/workspace/home-ops/infra/home-cluster$ talhelper genconfig
generated config for nuc.home-ops.k8s.mirceanton.com in ./clusterconfig/home-ops-nuc.home-ops.k8s.mirceanton.com.yaml
generated config for srv.home-ops.k8s.mirceanton.com in ./clusterconfig/home-ops-srv.home-ops.k8s.mirceanton.com.yaml
generated config for minisforum.home-ops.k8s.mirceanton.com in ./clusterconfig/home-ops-minisforum.home-ops.k8s.mirceanton.com.yaml
generated client config in ./clusterconfig/talosconfig
generated .gitignore file in ./clusterconfig/.gitignore
mike@home-ops-devbox:/workspace/home-ops/infra/home-cluster$ 
```

This is not really a problem if the file is sops-encrypted, as sops automatically removes that delimiter, but it threw me off a bit initially.

**Comment by budimanjojo** [comment]
@mirceanton yeah I noticed about this too before, it's an issue of the dotenv library that I'm using and I had plan to report this issue upstream but forgot. I'll open an issue there tomorrow. Thanks for the report! 😁

**Comment by budimanjojo** [comment]
I have reported the bug to the library repo: https://github.com/joho/godotenv/issues/217

**Comment by budimanjojo** [comment]
@mirceanton I don't think the upstream is gonna accept my PR since the library is not accepting PR (based on the pinned issue).

So I just fix it from here unless the upstream decided to fix this issue.

**Comment by mirceanton** [comment]
@budimanjojo Yeah, it seems they don't want to accept any more features. I think there are 2 options here:

- simply add a note in the documentation stating that, as a limitation of an upstream library, one should not use the delimiter in `talenv` files
- read the file -> check for delimiter -> pass it to the parser

**Comment by budimanjojo** [comment]
@mirceanton The commit I pushed that closes this issue is the fix, so there should be no more problem with having yaml document delimiter in `talenv.yaml` :wink:
