### ISSUE TITLE
[docs] Document env substitution using talenv(.sops).yaml

### ISSUE THREAD

**Issue by PrivatePuffin** [budimanjojo/talhelper#221]
I was looking into the correct structure of talenv, besides the fact it isn't that hard, I noticed that it also wasn't actually documented at-all.

It might be best to start documenting things like this.

**Comment by budimanjojo** [comment]
yes, after this commit: https://github.com/budimanjojo/talhelper/commit/b7824344dc38cd7f03d5d181f122b1d3e2c691f7

But it's more for people not using `sops` because talsecret.yaml is only used for secrets.

**Comment by budimanjojo** [comment]
I'm going to close this issue because of inactivity. Feel free to re open if you are not satisfied with my answer. Thank you.
