### ISSUE TITLE
[feat] Define bootstrap node and allow generating bootstrap command

### ISSUE THREAD

**Issue by Ornias1993** [budimanjojo/talhelper#223]
With 2 out of 3 most important commands done (apply and upgrade respectively), it would be nice if we could also generate the bootstrap command.

What we need for that, is to allow a single(!) controlplane node to be flagged as `bootstrap: true` (or something comparable).
Then we could use its IP to generate a bootstrap command as well.

**Comment by budimanjojo** [comment]
@Ornias1993 I'm not sure about adding `bootstrap: true` to the config file, what about having a `--node` flag just like the other `gencommand` subcommand?

**Comment by Ornias1993** [comment]
> @Ornias1993 I'm not sure about adding `bootstrap: true` to the config file, what about having a `--node` flag just like the other `gencommand` subcommand?

Thats cool! :)
Saves having to reference IPs all the time and just fetch it from the config file, thats the most important part imho!
