### ISSUE TITLE
[bug] images do not get "registered" with factory

### ISSUE THREAD

**Issue by Ornias1993** [budimanjojo/talhelper#232]
It seems that before images can be downloaded from the factory, they first need to be registed by making a get request towards the factory.

It would be best to implement this behavior where it's relevant. but the most logical place would likely be "genconfig", as that ensures the config build from said images references images that actually exist.

Maybe it would even be best to fetch the image strings from the factory directly, to ensure they are properly registered?

One might hit this when one has a order of extentions that does not match the website order (which would always trigger this) and/or is the first one to use a certain kernel argument and/or if one is the first to use a certain meta and/or if one is the first to pull a certain image at all.

---

The get request is documented here:
https://github.com/siderolabs/image-factory

---

Issues you hit when a image is not "registered" are shown here:

https://github.com/siderolabs/image-factory/issues/61

Though thoroughly underdocumented.

**Comment by budimanjojo** [comment]
Ah I didn't know about this. Seems like I need to change the way the schematic ID is getting parsed. I'll tackle this tomorrow. My plan is to use do a POST request to get the ID instead like the recommendation. It will also mean that it will require internet connection to generate the ID and will possibly fail in case the server is offline. Thanks for the report!

**Comment by Ornias1993** [comment]
> Ah I didn't know about this

yeah me neater, was breaking my head on this for 2 days and couldn't figure it out till the dev explained it's a registration/creation based API...

>  Seems like I need to change the way the schematic ID is getting parsed.

Cool, agreed, thanks for the quick response!

> My plan is to use do a POST request to get the ID instead like the recommendation

That should work

> It will also mean that it will require internet connection to generate the ID and will possibly fail in case the server is offline. Thanks for the report!

Think the old design is fine as long as it's an optional "offline mode"

> Thanks for the report!

No problem!

**Comment by budimanjojo** [comment]
Seems like the image factory is down this whole day so I can't do anything now :cry:

**Comment by Ornias1993** [comment]
> Seems like the image factory is down this whole day so I can't do anything now 😢

It's online for me at least...

**Comment by budimanjojo** [comment]
I'm unsure if `ofline` should be in flags or config because basically you'll only want online mode except when u/the server is down or u don't want to spam the server too much. Usually you want to register the id only once to the server so u can pull it. I need to rethink this thoroughly.
