### ISSUE TITLE
[bug] gencommand upgrade-k8s runs on more than 1 node

### ISSUE THREAD

**Issue by Ornias1993** [budimanjojo/talhelper#233]
We only need to run upgrade-k8s at a single (controlplane?) node.
By default it currently returns the command for all nodes

**Comment by budimanjojo** [comment]
Ah my bad! I made that in a hurry and totally forgot about this.
It's now acting like `bootstrap`.

**Comment by Ornias1993** [comment]
Cool that solves it :)
