### ISSUE TITLE
feature: add --dry-run parameter to: talhelper gencommand apply

### ISSUE THREAD

**Issue by bhuism** [budimanjojo/talhelper#324]
add --dry-un so that:

```talhelper gencommand apply```

generates command's with --dry-run as parameter in the apply-config commands

**Comment by budimanjojo** [comment]
Do you mean adding flags to the generated command? You can use `--extra-flags` for that: `talhelper gencommand apply --extra-flags "--dry-run"`

**Comment by bhuism** [comment]
Yes, or is this flag allready implemented

**Comment by budimanjojo** [comment]
Yes this flag is already there and u can use as many flags as you want, just put them in as string :)
