### ISSUE TITLE
System extensions example

### ISSUE THREAD

**Issue by runningman84** [budimanjojo/talhelper#381]
It would be great to have some example how to enable system extensions like iscsi. I tried the extensions parameter in the node object but got a deprecation warning in talosctl.

What is the correct way to that?

**Comment by budimanjojo** [comment]
Hi, @runningman84! Have you read the doc here? https://budimanjojo.github.io/talhelper/latest/guides/#adding-talos-extensions-and-kernel-arguments

**Comment by runningman84** [comment]
I tried that example once but did not see any change in the generated machine configs but I will try to reproduce that...

**Comment by runningman84** [comment]
sorry I used some old version of talhelper... the new one works!

**Comment by runningman84** [comment]
@budimanjojo with reset and re apply the extensions were active. Unfortunately after a node shutdown and start the extensions were lost again. Do you have any idea how that can happen?

**Comment by budimanjojo** [comment]
That's weird and I don't think it has anything to do with `talhelper` but rather the OS side problem. Maybe the log of the kernel might show you something.
