### ISSUE TITLE
[bug]: v1.5.6 is not a supported Talos version

### ISSUE THREAD

**Issue by N7KnightOne** [budimanjojo/talhelper#406]
I believe this is a bug as v1.5.X is listed as a supported version. 

```
There are issues with your talhelper config file:
field: "talosVersion"
  * "v1.5.6" is not a supported Talos version
2024/04/06 11:07:28 failed to parse config file: please fix issues with your config file
```

**Comment by budimanjojo** [comment]
You need to update your `talhelper`, it's now a warning instead of error and the latest version supports up to v1.6.x

**Comment by N7KnightOne** [comment]
You are correct! It seems the AUR needs to point to the latest version.
