### ISSUE TITLE
Add gencommand talosctl kubeconfig

### ISSUE THREAD

**Issue by runningman84** [budimanjojo/talhelper#432]
Creating a kubeconfig is a bit tricky because you have to know which endpoint to use:
````
talosctl kubeconfig .
command "kubeconfig" is not supported with multiple nodes
````
talhelper could just grab the endpoint from the talconfig which is https://${CLUSTER_VIP}:6443  in my case...

**Comment by budimanjojo** [comment]
There's `talhelper gencommand kubeconfig`. Are you on the latest `talhelper` release?

**Comment by runningman84** [comment]
Yes there is this command but my point is that it does not include the endpoint parameter so you get the error message…

**Comment by budimanjojo** [comment]
```
 talhelper gencommand kubeconfig
talosctl kubeconfig --talosconfig=./clusterconfig/talosconfig --nodes=192.168.200.11;
```

It does have endpoint, not sure why it's not on yours. Can you show me your `talconfig.yaml` file?

**Comment by runningman84** [comment]
sorry you are right... it was my fault.
