### ISSUE TITLE
Explain how to use the gencommand upgrade-k8s

### ISSUE THREAD

**Issue by runningman84** [budimanjojo/talhelper#433]
It is unclear to me how I can pass the to parameter, it might make sense to use the version defined in the talconfig as a default value which can be overwritten by some parameter...

````
➜  k8s-dev git:(main) ✗ talhelper gencommand upgrade-k8s
talosctl upgrade-k8s --talosconfig=./clusterconfig/talosconfig --to=v --nodes=10.0.30.81;
````

**Comment by budimanjojo** [comment]
Yes it should use the value defined in your `talconfig.yaml`. Do you have `kubernetesVersion` defined in your `talconfig.yaml`?

**Comment by budimanjojo** [comment]
Thank you for the report, fixed with https://github.com/budimanjojo/talhelper/commit/052729a0ebf202e6592993bbc3bb2acc1cf8c3e6
