### ISSUE TITLE
Documentation of secret handling

### ISSUE THREAD

**Issue by runningman84** [budimanjojo/talhelper#436]
For new users it might make sense to add the docs a bit.

* After a cluster is running, is it safe to run talhelper gensecret again? (or would you loose access to the cluster)?
* After a cluster is running for one year, you should gen a new config accouring to this docs: https://www.talos.dev/v1.7/talos-guides/howto/cert-management/#from-secrets-bundle  but how is this done in a given talhelper repo structure? It the same command beeing run every time you call talhelper genconfig?
* If you have files like talsecret.yaml and talsecret.sops.yaml which file is prefered? Would talhelper complain about differences?

Because secret management is very important in any talos cluster these things should be documented in order to ensure that you never loose access to your clusters.

**Comment by budimanjojo** [comment]
Thank you for the suggestions!

To answer the questions:

- You shouldn't update your `talsecret.yaml` file once your cluster is up and running as you will definitely lose access to the cluster.
- Running `talhelper genconfig` with the `talsecret.yaml` file in the `cwd` should re-request a brand new `talosconfig` just like `talosctl gen config --with-secrets secrets.yaml --output-types talosconfig -o talosconfig <cluster-name> https://<cluster-endpoint>` described in the docs you linked.
- `talhelper genconfig` command without `--secret-file` flag will by default try to find files in `cwd` named `talsecret.yaml`, `talsecret.sops.yaml`, `talsecret.yml`, `talsecret.sops.yml` in the order above with the latter found to take precedence. The same applied to `--env-file` flag. To make sure you have the right secret or env file, you can or should use the flag according to your need.

I will update the docs soon and link it to this issue.

**Comment by budimanjojo** [comment]
I think the third one is not worth the docs because it's very uncommon to have multiple `talsecret` files with different names in the `cwd` and if people are following the "Getting Started" guide it should be named `talsecret.sops.yaml`.
