### ISSUE TITLE
nodes[*].installDiskSelector.size should not be required

### ISSUE THREAD

**Issue by mrwulf** [budimanjojo/talhelper#47]
`nodes[*].installDiskSelector.size` is not actually required in the talos config. 

I tried using the size reported by `talosctl disks`, but that doesn't work (that's an issue with talos) -- it's probably a rounding error. For example, `talosctl disks` returns a size of 128 GB, but `talosctl dry-run -f node1.yaml` fails with "no disk found matching provided parameters".

As a workaround, switching the size to `<= 128.1 GB` makes everything work.

**Comment by budimanjojo** [comment]
Thank you! I will create a new release to fix this
