### ISSUE TITLE
Possible to use genurl when a node has a talosImageURL specified?

### ISSUE THREAD

**Issue by hagak** [budimanjojo/talhelper#480]
Currently if I call:
```
talhelper genurl installer --env-file main/bootstrap/talos/talenv.sops.yaml --config-file main/bootstrap/talos/talconfig.yaml
```
All nodes reference the factory.talos.dev however some of my nodes are using a custom talosImageURL so the factory url would be invalid for them.

**Comment by budimanjojo** [comment]
Hi @hagak!

I don't quite understand your question. Are you saying that (some of your nodes and not all?) you're using a selfhosted image factory and it's using different URL format?

Currently you can change the url format by doing this: https://budimanjojo.github.io/talhelper/latest/guides/#selfhosted-image-factory

But this will apply to all nodes and not single node.

**Comment by budimanjojo** [comment]
Sorry, I see what you mean now. I'll try to fix this now. Thank you!

**Comment by budimanjojo** [comment]
Please test the latest release (v2.4.9), thank you for reporting!

**Comment by hagak** [comment]
Just tested and that did it perfectly
