### ISSUE TITLE
[bug] No go releases for v2 onwards

### ISSUE THREAD

**Issue by Ornias1993** [budimanjojo/talhelper#494]
It seems the latest correctly released version when loading the go module is v1.17.1

It seems everything v2 and later is not correctly released.

**Comment by budimanjojo** [comment]
Do you mean this: https://pkg.go.dev/github.com/budimanjojo/talhelper?

Not sure if there's anything I can do to fix this. Do you have any idea on how this thing work?

**Comment by Ornias1993** [comment]
Yush precisely, I have no definitive idea, but i'll look into it!
(as I also have some project of my own that might someday hit similair snags)

**Comment by Ornias1993** [comment]
@budimanjojo Figured it, appearently its a safety feature, that requires a "v2" (or v3, v4 etc) in the path when bumping major versions.
Appearently goreleaser rejects it from being uploaded without throwing an error.

Source:
https://golang.cafe/blog/how-to-upgrade-to-a-major-version-in-go.html

**Comment by budimanjojo** [comment]
Thank you! Now I'm confused how do I fix this as those versions are released and I don't want to manually copy files into `v2` directory and push to each tag.
Now I feel like releasing v2 was a mistake :rofl:

**Comment by Ornias1993** [comment]
> Thank you! Now I'm confused how do I fix this as those versions are released and I don't want to manually copy files into `v2` directory and push to each tag. Now I feel like releasing v2 was a mistake 🤣

Honestly,
I think doing so retroactively is only going to be risky and not worth it...

So I would suggest just fixing it "for next version" and calling it a day...

**Comment by Ornias1993** [comment]
Sadly... Nope:
https://pkg.go.dev/github.com/budimanjojo/talhelper?tab=versions

**Comment by budimanjojo** [comment]
Yeah, I'll release it later. Still looking at something that I might miss

**Comment by Ornias1993** [comment]
Awesome, nice speedy work!

**Comment by Ornias1993** [comment]
Nice work!
