### ISSUE TITLE
[bug] TSEhelper not correctly included when importing a package

### ISSUE THREAD

**Issue by Ornias1993** [budimanjojo/talhelper#516]
Some packages import tsehelper.
However, the way thats done, makes it seemlingly impossible to import those packages without:
A. adding tsehelper directly into your codebase
And
B. copying the replace directive in go.mod

This seems crude and unneeded for such a small module.

---

Suggested solutions:
A. Include TSEhelper as a package instead
or 
B. ensure the module is correctly published and versioned

**Comment by budimanjojo** [comment]
Maybe I should make it a proper module instead. I'll tackle this when I have free time. Thank you for reporting!

**Comment by Ornias1993** [comment]
> Maybe I should make it a proper module instead. I'll tackle this when I have free time. Thank you for reporting!

Spot on as always!
Thanks for your speedy reply :)

**Comment by Ornias1993** [comment]
@budimanjojo tested importing talhelper just now, worked perfectly even without tsehelper, thanks! :)
