### ISSUE TITLE
Labels nodes with schematic

### ISSUE THREAD

**Issue by Ornias1993** [budimanjojo/talhelper#522]
Talhelper currently features create logic to create and register schematic IDs
It would be nice, if we could add a label to each node, with its schematic_id

That way other in-cluster tooling, like system-upgrade-controller, can fetch the schematic-id as well.

**Comment by budimanjojo** [comment]
You can add node labels with `nodes[index].nodeLabels`. But you need to use `nodes[index].talosImageURL` instead of `nodes[index].schematic` for that to work.

I'm unsure if adding labels to node by default is something I want to do. Can you provide how do you want this to be implemented?

**Comment by Ornias1993** [comment]
> You can add node labels with `nodes[index].nodeLabels`. But you need to use `nodes[index].talosImageURL` instead of `nodes[index].schematic` for that to work.

I'm not sure I follow how I can automatically have nodes labeled with their schematic this way

> I'm unsure if adding labels to node by default is something I want to do. Can you provide how do you want this to be implemented?

If a node is labeled a certain way, we can fetch this info from within kubernetes. which we currently, cannot.

**Comment by budimanjojo** [comment]
> I'm not sure I follow how I can automatically have nodes labeled with their schematic this way

Something like this?
```yaml
nodes:
  - name: a-node
    talosImageURL: https://blablabla/${schematicID}
    nodeLabels:
      schematic: ${schematicID}
```

**Comment by Ornias1993** [comment]
Yeah which would completely destroy the whole extention selection system.

**Comment by budimanjojo** [comment]
True, I don't know how should this be implemented without making it a default. Maybe you can provide an example `talconfig.yaml` that you want this feature to be implemented so I can see what can be done?

**Comment by Ornias1993** [comment]
> True, I don't know how should this be implemented without making it a default. Maybe you can provide an example `talconfig.yaml` that you want this feature to be implemented so I can see what can be done?

I'm explicitly asking for just by default labeling nodes with their respective schematic-id.
there is literally no reason that an extra label like that is harmfull, why it *is* usefull.

**Comment by budimanjojo** [comment]
I never say it's harmful. But adding something that the user doesn't explicitly set in the config file is something I really don't want to do.

I'll think about how this can be implemented without adding it by default (I don't even know what's the proper label key for this and what `system-upgrade-controller` expect as I don't use it. I'll have a deeper look on this when I have time.

**Comment by Ornias1993** [comment]
> I don't even know what's the proper label key for this and what system-upgrade-controller expect as I don't use it. I'll have a deeper look on this when I have time.

system-upgrade-controller doesn't "expect" anything, thats something the user configures themselves.
I would be fine with you calling it "your-mom-on-a-tricicle", as long as this info is available *in any way* in-cluster on a per-node basis.
Which means: node labels.

> But adding something that the user doesn't explicitly set in the config file is something I really don't want to do.
The point is:
We've no way of knowing the schematic id in cluster currently AT ALL.

---

I wanted to request this for the benefid of many, but i'll just implement it myself in go.
Shame.

**Comment by budimanjojo** [comment]
> The point is:
We've no way of knowing the schematic id in cluster currently AT ALL.

There are a lot of things that are no way to know in cluster right now, and I never say this is a bad idea or anything but I need a more detail explanation on what and how this should be implemented that you never provide. I don't use `system-upgrade-controller` and I don't know anything about it.

> I wanted to request this for the benefid of many, but i'll just implement it myself in go.
Shame.

Nice, then I'll close this issue. Thank you!

**Comment by Ornias1993** [comment]
> I don't use system-upgrade-controller and I don't know anything about it.

As I tried to explain, system-upgrade-controller is just a single *example*.
I don't need your help on that, I just need this information cluster exposed.

To do *any* side of talos images actions on the cluster, this info needs to be available on cluster. Regardless of which tool one uses.

I just need it, in any way, on a per-node basis available on the cluster.
How I personally deal with setting up my tools, is not really a concern.


> Nice, then I'll close this issue. Thank you!

I find this a pretty short sighted reply tbh.
I try to help out, but you basically are asking me for something that isn't relevant, as system-upgrade-controler has nothing to do with it. So please stop asking about it.

I just need that info available in-cluster.
**how** or **how its used** is not the issue here.,
