### ISSUE TITLE
config validation with custom images needs to be bypassed

### ISSUE THREAD

**Issue by samip5** [budimanjojo/talhelper#537]
```
$ talhelper genconfig -d
2024/07/14 12:17:13 DEBUG start loading and validating config file
2024/07/14 12:17:13 DEBUG reading talconfig.yaml
2024/07/14 12:17:13 DEBUG substituting config file with environment variable
2024/07/14 12:17:13 DEBUG overriding global controlplane node config for m1
2024/07/14 12:17:13 DEBUG overriding global worker node config for w-amd-1
2024/07/14 12:17:13 DEBUG overriding global worker node config for w-amd-2
2024/07/14 12:17:13 DEBUG overriding global worker node config for w-amd-3
2024/07/14 12:17:13 DEBUG overriding global worker node config for w7
2024/07/14 12:17:13 DEBUG start validating talconfig file
2024/07/14 12:17:13 DEBUG validating config file for node m1
2024/07/14 12:17:13 DEBUG validating config file for node w-amd-1
2024/07/14 12:17:13 DEBUG validating config file for node w-amd-2
2024/07/14 12:17:13 DEBUG validating config file for node w-amd-3
2024/07/14 12:17:13 DEBUG validating config file for node w7
There are issues with your Talhelper config file:
field: "nodes[4].schematic"
  * sbc-raspberrypi (registry.skysolutions.fi/library/sbc-raspberrypi:alpha.1-1@sha256:f5734630fbae0647daf6e490ff91cd5f95220c3fc34e64364b2f245cde502a43) is not a supported Talos overlay for "v1.7.5"
field: "talosVersion"
  * WARNING: "v1.8.0-alpha.1" might not be compatible with this Talhelper version you're using
2024/07/14 12:17:13 failed to parse config file: please fix issues with your config file
```

My config snippet:
```yaml
talosVersion: 1.8.0-alpha.1

<omitted>

nodes:
    - hostname: w7
      ipAddress: 10.0.105.29
      controlPlane: false
      installDiskSelector:
        wwid: naa.5002538f4173a3bc
      talosImageURL: registry.skysolutions.fi/library/installer:v1.8.0-alpha.1-1
      schematic:
        overlay:
          name: sbc-raspberrypi
          image: registry.skysolutions.fi/library/sbc-raspberrypi:alpha.1-1@sha256:f5734630fbae0647daf6e490ff91cd5f95220c3fc34e64364b2f245cde502a43
      disableSearchDomain: true
      networkInterfaces:
        - deviceSelector:
            hardwareAddr: d8:3a:dd:d8:70:bc
          dhcp: true

**Comment by budimanjojo** [comment]
Thanks for reporting this issue @samip5!

Seems like you're not using the official image factory and the validation checks in the official repo hence the fail.
Maybe I should make a switch to turn off the validation?

But there's one problem with your config too. If you're using `talosImageURL`, it will skip creating the schematic id from `schematic` for you and just use the provided `talosImageURL`.

There's a way to use selfhosted image factory: https://budimanjojo.github.io/talhelper/latest/guides/#selfhosted-image-factory but it won't work too because I messed up with the validation thing :rofl:

**Comment by budimanjojo** [comment]
I just created a PR that will not exit on failed validation.
Meanwhile, please have something like this in your `talconfig.yaml` file and use your selfhosted image factory:
```yaml
imageFactory:
  registryURL: registry.skysolutions.fi/library
  schematicEndpoint: /schematics
  protocol: http
  installerURLTmpl: {{.RegistryURL}}/installer/{{.ID}}:{{.Version}}
nodes:
  - hostname: w7
    ipAddress: 10.0.105.29
    controlPlane: false
    installDiskSelector:
      wwid: naa.5002538f4173a3bc
    schematic:
      overlay:
        name: sbc-raspberrypi
        image: registry.skysolutions.fi/library/sbc-raspberrypi:alpha.1-1@sha256:f5734630fbae0647daf6e490ff91cd5f95220c3fc34e64364b2f245cde502a43
```

See if it works and report back (with the patch from the PR above of course, should I give you the binary file to test?). Thank you!

**Comment by budimanjojo** [comment]
[binary.tar.gz](https://github.com/user-attachments/files/16228066/binary.tar.gz)

Here's the binary to test.

**Comment by samip5** [comment]
Unfortunately, I don't use a factory but instead the images are pushed outside of using that so it would still fail.

**Comment by budimanjojo** [comment]
Ah okay. So what you need is a switch to turn off schematic validation. I'll create a PR for it later. Wondering if I should create a flag or a yaml field for that.

**Comment by budimanjojo** [comment]
> so it would still fail as the schematic url is not reachable.

Not if you provide `--offline-mode` flag to the `genconfig` flag.

**Comment by samip5** [comment]
> Ah okay. So what you need is a switch to turn off schematic validation. I'll create a PR for it later. Wondering if I should create a flag or a yaml field for that.

Preferably a yaml field as flags are easy to forget.

**Comment by budimanjojo** [comment]
Please test the newest release (v3.0.4) and add `noSchematicValidate: true` at node level. Should now run successfully. And please remove the `talosImageURL` in that node for the schematic id to be generated. Thank you for reporting the issue!
