### ISSUE TITLE
Removing `-` does not reflect in the config

### ISSUE THREAD

**Issue by joryirving** [budimanjojo/talhelper#546]
I was trying to swap from `literal block scalar with strip` to `literal block scalar` by swapping from `|-` to just `|`.
https://github.com/joryirving/home-ops/commit/60070ca19a6856324ac16ac7423bed2de03a490a

However when I run `talhelper genconfig`, the generated file keeps using the `|-`, stripping the newline from the end of the block, that I need to maintain.

The reason for this was stated in the home-operations discord here:
https://discord.com/channels/673534664354430999/942576972943491113/1265464659163742360

**Comment by budimanjojo** [comment]
Thanks for reporting. Is the line in this screenshot (taken from the commit you linked above) supposed to be `|-` and not `|`?
![image](https://github.com/user-attachments/assets/ad071bda-fd3b-4131-9ca7-87c394ec78ff)

**Comment by joryirving** [comment]
Thanks for pointing out I'm blind in a kind way. I had to remove both, but that fixed it for me.
