### ISSUE TITLE
Add dryRun option to goreleaser workflow

### ISSUE THREAD

**Issue by mircea-pavel-anton** [budimanjojo/talhelper#568]
Having the workflow do a dryRun on any PR that modifies the workflow file would allow us to test those changes (such as renovate updates) automatically and enable automerge on them

**Comment by budimanjojo** [comment]
Thank you!

**Comment by mircea-pavel-anton** [comment]
@budimanjojo I think this should be as simple as adding the 'snapshot' flag like this:

* https://github.com/mirceanton/reusable-workflows/blob/v1.0.0/.github/workflows/go-release.yaml#L55

You can see an example run of this here:

* https://github.com/mirceanton/kube-switcher/actions/runs/10752026739/job/29819896577

What do you think?

**Comment by budimanjojo** [comment]
Go ahead, I don't see there will be any problem having it. Thank you!
