### ISSUE TITLE
[Downstream] Weird behavior on 3.0.6

### ISSUE THREAD

**Issue by PrivatePuffin** [budimanjojo/talhelper#645]
When calling  directly `GenerateConfig` directly on 3.0.6 it throws:

`yaml: expected STREAM-START error="yaml: expected STREAM-START"`

Whereas the same command on 3.0.5 runs perfectly fine.

In both versions: `LoadAndValidateFromFile` does not throw any errors.

In the changes I see some envsubst changes are applied, primarily in regards to comment handeling, however I dont see much that can cause this weird error.

**Comment by budimanjojo** [comment]
Thanks for reporting!

Do you have some data that I can test with?

**Comment by PrivatePuffin** [comment]
@budimanjojo I can get you access to our codebase so I can send you the implementation of this specific function...
Its a rather straight-forward call to the function thats what makes me frown about this specific error.

Even more so because you didn't really change much at all.

**Comment by PrivatePuffin** [comment]
@budimanjojo Issue seems to have magically resolved itself on 3.0.7

**Comment by PrivatePuffin** [comment]
Actually no it doesn't, 3.0.7 introduced another change:
@./ in 3.0.7 now refers to the path of talconfig.yaml whereas in 3.0.5 (and I think 3.0.6) it referred to the directory the code is executed from. (this is a breaking change btw, I think caused by a dependency update)


However, when the patch paths are fixed to account for that, this error still shows:
`yaml: expected STREAM-START error="yaml: expected STREAM-START"`

**Comment by PrivatePuffin** [comment]
The weird part about it, is that all yaml checks out when manually checked, even the validator accepts the files.

I first suspected there was some issue with commenting, but when I remove comments from all files, same issue.
(which is odd, because the comment handling is the primary thing changed in 3.0.6 it looks like)

**Comment by budimanjojo** [comment]
I'll take a look

**Comment by budimanjojo** [comment]
I don't know how to run the problem in your code. My guess is you have a file (a patch or something) that is an empty yaml file?

**Comment by PrivatePuffin** [comment]
YES, that's indeed the case...
Good catch!

**Comment by budimanjojo** [comment]
May I know where is the the empty file being called (I tried calling in `patches` and the error is different from yours) so I can fix this?

**Comment by budimanjojo** [comment]
Found the problem, will be fixed in next release. Thank you!

**Comment by PrivatePuffin** [comment]
> May I know where is the the empty file being called (I tried calling in `patches` and the error is different from yours) so I can fix this?

Yeah so we had 1 empty patch files.
I, for now, put some filler into them and it worked flawlessly.

Also another issue is the fact that the relative path references have changed, see:
```
@./ in 3.0.7 now refers to the path of talconfig.yaml whereas in 3.0.5 (and I think 3.0.6) it referred to the directory the code is executed from. (this is a breaking change btw, likely caused by https://github.com/budimanjojo/talhelper/pull/619)
```

**Comment by PrivatePuffin** [comment]
> Found the problem, will be fixed in next release. Thank you!

Awesome!

**Comment by budimanjojo** [comment]
Yes, the change to relative path reference is intented so you can run `talhelper genconfig` command not only from the path where `talconfig.yaml` file is located.
