### ISSUE TITLE
BUG: cni config field is required but tagged as optional

### ISSUE THREAD

**Issue by tzabbi** [budimanjojo/talhelper#649]
Hey there, I'm using talhelper first time. Everything works great!

I encounter an issue with the cni config. In the documentations it is marked as optional but when I don't specify it `talhelper genconfig` throughs an error:
![image](https://github.com/user-attachments/assets/ce1985d2-7af7-4b61-82b2-b054d34dc8f8)

If it is really an bug, I can provide an fix but don't investigate it for now.

Thanks 
Tom

**Comment by budimanjojo** [comment]
Hey @tzabbi, thanks for reporting!

I just tried `genconfig` command locally without `cniConfig` specified and the command ran fine. Can you provide your `talconfig.yaml`?

**Comment by budimanjojo** [comment]
The check will only run if `cniConfig` is defined: https://github.com/budimanjojo/talhelper/blob/94c2348d36537b917975a82c0089e5b454995445/pkg/config/validator.go#L196

Are you sure you don't have it defined somewhere in your config file? Also make sure you're running the latest version of Talhelper.

**Comment by tzabbi** [comment]
Strange I cloudn't reproduce it. So I will close it. Sorry for the inconvenience.
