### ISSUE TITLE
How to upgrade talos via talosctl 

### ISSUE THREAD

**Issue by tzabbi** [budimanjojo/talhelper#654]
I can see that talhelper will generate a talconfig controlplane.yaml with an image id. When I apply this config, it does not install the image which is refered to. How can I upgrade my talos os when another image is refered in talosconfig of the controlplane.yaml?

**Comment by budimanjojo** [comment]
You can't upgrade using `talosctl apply-config` command to update the image of your node. You should use `talosctl upgrade` command instead.
Using `talhelper`, you can do it like so: `talhelper gencommand upgrade -n <node name or ip>` and run the generated command.

**Comment by tzabbi** [comment]
Thank you!
